# Generated by Django 4.2.2 on 2023-06-09 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=15)),
                ('exam_date', models.DateField(auto_now=True)),
                ('max_score', models.IntegerField(default=93)),
                ('actual_score', models.IntegerField()),
                ('Percentage', models.IntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.studentdetails')),
            ],
        ),
    ]
