# Generated by Django 4.2.2 on 2023-06-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0003_rename_percentage_examdetails_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetails',
            name='grade',
            field=models.BooleanField(default=True),
        ),
    ]
