# Generated by Django 4.2.2 on 2023-06-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productslist',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
