# Generated by Django 4.2.2 on 2023-06-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0002_productslist_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouritesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourites', models.ManyToManyField(to='productApp.productslist')),
            ],
        ),
    ]
