# Generated by Django 4.2.2 on 2023-06-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0003_favouriteslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='productslist',
            name='archive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productslist',
            name='favourites',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productslist',
            name='date_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='FavouritesList',
        ),
    ]
