# Generated by Django 4.2.2 on 2023-06-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0004_productslist_archive_productslist_favourites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
