# Generated by Django 4.2.2 on 2023-06-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0005_alter_productslist_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='date_time',
            field=models.DateField(auto_now=True),
        ),
    ]
