# Generated by Django 4.2.2 on 2023-06-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0006_alter_productslist_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='productslist',
            name='product_description',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
