# Generated by Django 4.2.2 on 2023-06-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0007_productslist_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslist',
            name='product_description',
            field=models.TextField(max_length=500),
        ),
    ]
