# Generated by Django 4.2.2 on 2023-06-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0008_alter_productslist_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productslist',
            name='pad_id',
            field=models.IntegerField(default=0),
        ),
    ]
