# Generated by Django 4.2.2 on 2023-06-13 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0009_productslist_pad_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productslist',
            name='pad_id',
        ),
    ]
