# Generated by Django 4.2.2 on 2023-06-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_qty', models.IntegerField(default=0)),
                ('product_price', models.IntegerField()),
                ('total_price', models.IntegerField()),
            ],
        ),
    ]
